apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.appname }}-lb
  namespace: default
  labels:
    app.kubernetes.io/name: {{ .Values.deployment.appname }}-lb
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.deployment.appname }}
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP