apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.Name | default "db-secrets" }}
type: Opaque
data:
  root_password: {{ .Values.secret.rootPassword | b64enc }}
  db_name: {{ .Values.secret.databaseName | b64enc }}
  username: {{ .Values.secret.username | b64enc }}
  password: {{ .Values.secret.password | b64enc }}