apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.appname }}-service
  labels:
    app: {{ .Values.deployment.appname }}-service
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default "8080" }}
      targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: {{ .Values.deployment.appname }}